site_name: YinKH
site_description: "YinKH个人博客"

docs_dir: blogs
site_dir: docs

theme:
  name: "material"

nav:
  - 主页: index.md
  - FastApi+Uvicorn使用logrotate压缩access日志后新日志无法正常输出: fastapi_uvicorn_logrotate.md

copyright: Copyright &copy; 2021 <a href="https://www.yinkh.top/">YinKH</a>